name: Hello Action
author: Japneet Sahni
description: Hello World Action
inputs:
  who-to-greet:
    description: 'Input for person to be greeted'
    required: true
    default: Japneet
outputs:
  time:
    description: 'time'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}