name: Actions Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: List directory
        run: |
          pwd
          ls -la
      - name: Run JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Japneet'
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time}}"
        