name: Actions Workflow
env:
  WF_ENV: ${{ secrets.WF_ENV }}
on:
  push:
    branches: 
      - main
      - 'feature/*' # matches feature/feata, feature/featb, ignore /
      - 'feature/**' # matches feature/feat/a
      - '!release'
  pull_request:
    branches: 
      - main
    tags:
      - v1
    # paths:
    #   - '**.js' # Only triggered when there is a change in JS file.
    #   - '!abc.js' # Triggered on JS file except abc.js
    # branches-ignore: # You can't have both branches and branches-ignore at same time
    #   - develop
    types: # These 3 are default values
      - opened
      - reopened
      - syncronized 
  # schedule:
  #   - cron: "30 3 * * *"
  repository_dispatch: # Triggered by an external event
  # POST https://api.github.com/repos/{owner}/{repo}/dispatches
  # Body : {"event_type":"build", "client_payload": {"env":"production"}}
  # Authorization: Personal access tokens with repo scope
    types: 
      - build

jobs:
  prod-check: # Uses github context
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
  run-env-variables:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps inside this job
    steps:
      - name: Repository Dispatch payload
        run: echo "${{ github.event.client_payload.env }}" # Uses github context
      - name: Log Env variables
        env:
          STEP_ENV: Available to only this step
        run: |
          echo "GITHUB_CONTEXT: ${{ toJSON(github) }}"
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  run-checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: List directory
        run: |
          pwd
          ls -la
      - name: Run JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Japneet'
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time}}" # Uses steps context
        