name: Container workflow

on:
  pull_request:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:alpine3.17
    steps:
      - name: log npm version
        run: |
          node -v
          cat /etc/os-release
      - name: Step with its own docker container
        # a step cannot have both the `uses` and `run` keys
        uses: docker://node:18-alpine3.16
        with:
          entrypoint: /usr/local/bin/node
          args: -v
