name: Container workflow

on:
  push:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:alpine3.17
    steps:
      - name: log npm version
        run: |
          node -v
          cat /etc/os-release
      - name: Step with its own docker container
        uses: docker://node:18-alpine3.16
        run: |
          node -v
          cat /etc/os-release
