name: Custom Action Workflow

on:
  push:
    branches: [main]

jobs:
  run-custom-docker-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run custom JS action
        id: greet
        uses: ./.github/actions/hello
        with:
          who-to-greet: 'Supreet'
      - name: Log greeting time
        run: |
          echo "${{ steps.greet.outputs.time}}"
          echo $HELLO